<?php
$products = [
    // === ОГОНЬ ===
    'salamander-dance' => [
        'element' => 'fire',
        'panorama' => 'images/11111.jpg',
        'image' => 'images/7cb30623-ddb0-443c-9713-7c5fefdde624.jpg',
        'secondary' => 'images/a827ae2a-dcae-4d4e-8124-1e81b38ceb7c.jpg',
        'tag_key' => 'product_fire_tag',
        'type_key' => 'product_fire_type',
        'name' => 'Танец Саламандры',
        'name_key' => 'fire_product_1_name',
        'price' => 6900,
        'price_note_key' => 'product_fire_price_note',
        'story' => '<span class="dropcap gold-text-contrast">Э</span>то колье хранит в себе искру вечного огня и силу стихии.',
        'story_key' => 'story_salamander_dance',
        'button_key' => 'product_fire_button',
    ],
    'phoenix-ash' => [
        'element' => 'fire',
        'panorama' => 'images/photo_2026-06-07_10-37-48.jpg',
        'image' => 'images/12fkj.png',
        'secondary' => 'images/photo_2026-06-07_10-37-50.jpg',
        'tag_key' => 'product_fire_tag',
        'type_key' => 'product_fire_type',
        'name' => 'Пепел Феникса',
        'name_key' => 'fire_product_2_name',
        'price' => 7900,
        'price_note_key' => 'product_fire_price_note',
        'story' => '<span class="dropcap gold-text-contrast">Т</span>ам, где пламя танцует, рождается магия. Это колье соткано из красных капель настоящего коралла и круглого гематита, сверкающего серебряным бисером.',
        'story_key' => 'story_phoenix_ash',
        'button_key' => 'product_fire_button',
    ],
    'heart-of-sun' => [
        'element' => 'fire',
        'panorama' => 'images/photo_2026-06-07_10-38-35.jpg',
        'image' => 'images/71c8e4b0-5210-4fdc-a856-0a9f2a7b7d7c.jpg',
        'secondary' => 'images/094b4c63-a5f9-4a7c-a532-c5906338fc1c.png',
        'tag_key' => 'product_fire_tag',
        'type_key' => 'product_fire_type',
        'name' => 'Сердце Солнца',
        'name_key' => 'fire_product_3_name',
        'price' => 7900,
        'price_note_key' => 'product_fire_price_note',
        'story' => '<span class="dropcap gold-text-contrast">Я</span>нтарь, огненный бисер — это искра вечного солнца.',
        'story_key' => 'story_heart_of_sun',
        'button_key' => 'product_fire_button',
    ],
    
    // === ВОДА ===
    'mermaid-tears' => [
        'element' => 'water',
        'panorama' => 'images/photo_2026-06-08_15-47-14.jpg',
        'image' => 'images/photo_2026-06-28_10-33-57.jpg',
        'secondary' => 'images/photo_2026-06-08_15-47-11.jpg',
        'tag_key' => 'product_water_tag',
        'type_key' => 'water_jewelry_type',
        'name' => 'Слезы Русалки',
        'name_key' => 'water_product_1_name',
        'price' => 8900,
        'price_note_key' => 'product_water_price_note',
        'story' => '<span class="dropcap gold-text-contrast">К</span>апля, упавшая с ресниц морской девы. Стразы, настоящий лунный камень — шёпот морских волн.',
        'story_key' => 'story_mermaid_tears',
        'button_key' => 'product_water_button',
    ],
    'moon-tide' => [
        'element' => 'water',
        'panorama' => 'images/photo_2026-06-07_10-39-02.jpg',
        'image' => 'images/photo_2026-06-28_10-33-58.jpg',
        'secondary' => 'images/photo_2026-06-07_10-39-07.jpg',
        'tag_key' => 'product_water_tag',
        'type_key' => 'water_jewelry_type',
        'name' => 'Лунный Прилив',
        'name_key' => 'water_product_2_name',
        'price' => 6900,
        'price_note_key' => 'product_water_price_note',
        'story' => '<span class="dropcap gold-text-contrast">С</span>вет луны, застывший в колье. Это украшение хранит тайны подводного мира и дыхание океана.',
        'story_key' => 'story_moon_tide',
        'button_key' => 'product_water_button',
    ],
    'pearl-depths' => [
        'element' => 'water',
        'panorama' => 'images/photo_2026-06-07_10-38-26.jpg',
        'image' => 'images/3333.jpg',
        'secondary' => 'images/970b1ce7-d2fb-4b2b-bfbe-e973d49defee.jpg',
        'tag_key' => 'product_water_tag',
        'type_key' => 'water_jewelry_type',
        'name' => 'Жемчужина Глубин',
        'name_key' => 'water_product_3_name',
        'price' => 5900,
        'price_note_key' => 'product_water_price_note',
        'story' => '<span class="dropcap gold-text-contrast">Т</span>ам, где молчит океан, рождается жемчуг. А главное украшение — это краб, который его оберегает.',
        'story_key' => 'story_pearl_depths',
        'button_key' => 'product_water_button',
    ],
    
    // === ЗЕМЛЯ ===
    'tree-roots' => [
        'element' => 'earth',
        'panorama' => 'images/photo_2026-06-07_10-37-58.jpg',
        'image' => 'images/999.jpg',
        'secondary' => 'images/photo_2026-06-08_15-47-34.jpg',
        'tag_key' => 'product_earth_tag',
        'type_key' => 'earth_jewelry_type',
        'name' => 'Корни Дерева',
        'name_key' => 'earth_product_1_name',
        'price' => 8900,
        'price_note_key' => 'product_earth_price_note',
        'story' => '<span class="dropcap gold-text-contrast">Т</span>ам, где корни уходят в вечность. Это украшение хранит в себе силу земли и дыхание древнего леса.',
        'story_key' => 'story_tree_roots',
        'button_key' => 'product_earth_button',
    ],
    'omni-sprouts' => [
        'element' => 'earth',
        'panorama' => 'images/photo_2026-06-08_15-47-21.jpg',
        'image' => 'images/222.jpg',
        'secondary' => 'images/photo_2026-06-08_15-47-24.jpg',
        'tag_key' => 'product_earth_tag',
        'type_key' => 'earth_jewelry_type',
        'name' => 'Побеги Омни',
        'name_key' => 'earth_product_2_name',
        'price' => 7900,
        'price_note_key' => 'product_earth_price_note',
        'story' => '<span class="dropcap gold-text-contrast">Л</span>иства, сплетённая из бисера. Каждый побег хранит в себе жизненную силу земли.',
        'story_key' => 'story_omni_sprouts',
        'button_key' => 'product_earth_button',
    ],
    'lilac-rose' => [
        'element' => 'earth',
        'panorama' => 'images/photo_2026-06-07_10-38-51.jpg',
        'image' => 'images/888.jpg',
        'secondary' => 'images/3b8db7fe-8483-4fc4-a03e-b4e1ed01b92a.png',
        'tag_key' => 'product_earth_tag',
        'type_key' => 'earth_jewelry_type',
        'name' => 'Сиреневая Роза',
        'name_key' => 'earth_product_3_name',
        'price' => 8900,
        'price_note_key' => 'product_earth_price_note',
        'story' => '<span class="dropcap gold-text-contrast">К</span>амень, в котором застыла душа цветка. Сиреневая роза хранит в себе нежность и магию весеннего леса.',
        'story_key' => 'story_lilac_rose',
        'button_key' => 'product_earth_button',
    ],
    
    // === ВОЗДУХ ===
    'phoenix-feather' => [
        'element' => 'air',
        'panorama' => 'images/photo_2026-06-07_10-39-00.jpg',
        'image' => 'images/photo_2026-06-28_10-33-56.jpg',
        'secondary' => 'images/photo_2026-06-07_10-38-58.jpg',
        'tag_key' => 'product_air_tag',
        'type_key' => 'air_jewelry_type',
        'name' => 'Перо Феникса',
        'name_key' => 'air_product_1_name',
        'price' => 6900,
        'price_note_key' => 'product_air_price_note',
        'story' => '<span class="dropcap gold-text-contrast">П</span>еро выпало и остыло. Перо Феникса хранит в себе дыхание небес и лёгкость ветра.',
        'story_key' => 'story_phoenix_feather',
        'button_key' => 'product_air_button',
    ],
    'stardust' => [
        'element' => 'air',
        'panorama' => 'images/photo_2026-06-07_10-38-41.jpg',
        'image' => 'images/1a6a3685-122b-4ba8-8695-12ce4f833450.jpg',
        'secondary' => 'images/photo_2026-06-07_10-38-40.jpg',
        'tag_key' => 'product_air_tag',
        'type_key' => 'air_jewelry_type',
        'name' => 'Звездная Пыль',
        'name_key' => 'air_product_2_name',
        'price' => 5900,
        'price_note_key' => 'product_air_price_note',
        'story' => '<span class="dropcap gold-text-contrast">О</span>сколки далёких миров, собранные в ожерелье. Звёздная пыль хранит в себе свет ночного неба.',
        'story_key' => 'story_stardust',
        'button_key' => 'product_air_button',
    ],
    'breath-of-spring' => [
        'element' => 'air',
        'panorama' => 'images/photo_2026-06-07_10-38-31.jpg',
        'image' => 'images/444.jpg',
        'secondary' => 'images/photo_2026-06-07_10-37-43.jpg',
        'tag_key' => 'product_air_tag',
        'type_key' => 'air_jewelry_type',
        'name' => 'Дыхание Весны',
        'name_key' => 'air_product_3_name',
        'price' => 4900,
        'price_note_key' => 'product_air_price_note',
        'story' => '<span class="dropcap gold-text-contrast">Д</span>ыхание весеннего ветра, застывшее в сиреневых цветах из полимерной глины. Хранит лёгкость и свободу лепестков.',
        'story_key' => 'story_breath_of_spring',
        'button_key' => 'product_air_button',
    ],
];
?>